name: Deploy
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "npm run build"

      - name: Build step
        run: "pm2 start dist/index.js --name \"deepseek-free-api\""

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "deepseek-fr-84"
          entrypoint: "src/index.ts"
          root: ""
          
          
